### ISSUE TITLE
Problem with folium plots

### ISSUE THREAD

**Issue by IlyaOrson** [gboeing/osmnx#113]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)

Hello! None of the examples from [notebook 11
](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/11-plot-routes-folium-web-map.ipynb) is working for me. ~The IFrame commands give me an 404 error, although I confirmed the existance of the files in the path with `os.path.isfile(filepath)`~. When I try to open the files manually in a browser, both `graph.html` and `route_graph.html` show a blank page, while `route.html` shows an interactive map of the location but no route at all. 

#### What operating system, architecture, Python version, and OSMnx version are you using?
I am on Windows 7, using python 3.6.1 from Anaconda 4.3.30. 

#### Complete list of your environment's packages and their versions (for example, run `conda list` or `pip list` then paste the output below)

The list is incomplete because is hard to copy it from windows terminal. FWIW, I have folium 0.5.
<details>
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gnutls              3.4.11                        2
m2w64-grep                2.24                          2
m2w64-gsl                 2.1                           2
m2w64-jansson             2.7                           3
m2w64-libffi              3.2.1                         4
m2w64-libiconv            1.14                          6
m2w64-libidn              1.32                          4
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libmetalink         0.1.3                         2
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libssh2             1.7.0                         2
m2w64-libsystre           1.0.1                         3
m2w64-libtasn1            4.7                           2
m2w64-libtiff             4.0.6                         2
m2w64-libtre-git          122.c2f5d13                   5
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-nettle              3.1.1                         4
m2w64-nghttp2             1.9.2                         2
m2w64-nlopt               2.4.2                         3
m2w64-openssl             1.0.2.g                       2
m2w64-p11-kit             0.23.2                        2
m2w64-pcre                8.38                          2
m2w64-rtmpdump-git        499.a107cef                   4
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markupsafe                0.23                     py36_2
matplotlib                2.0.2               np112py36_0
mccabe                    0.6.1            py36hb41005a_1    anaconda
menuinst                  1.4.7                    py36_0
mistune                   0.7.4                    py36_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_1
msgpack-python            0.4.8                    py36_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py36_0
munch                     2.2.0                    py36_0    conda-forge
navigator-updater         0.1.0                    py36_0
nbconvert                 5.1.1                    py36_0
nbformat                  4.3.0                    py36_0
networkx                  2.0                      py36_1    conda-forge
nltk                      3.2.3                    py36_0
nose                      1.3.7                    py36_1
notebook                  5.0.0                    py36_0
numba                     0.33.0              np112py36_0
numexpr                   2.6.2               np112py36_0
numpy                     1.12.1                   py36_0
numpydoc                  0.6.0                    py36_0
oauth2client              4.1.2                     <pip>
odo                       0.5.0                    py36_1
olefile                   0.44                     py36_0
openjpeg                  2.1.2                    vc14_3  [vc14]  conda-forge
openpyxl                  2.4.7                    py36_0
openssl                   1.0.2l           vc14hf4c37d5_5  [vc14]  anaconda
osmnx                     0.6                      py36_1    conda-forge
packaging                 16.8                     py36_0
pandas                    0.21.0           py36he09d4dd_1
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.1                    py36_0
partd                     0.3.8                    py36_0
path.py                   10.3.1                   py36_0
pathlib2                  2.2.1                    py36_0
patsy                     0.4.1                    py36_0
pcre                      8.39                     vc14_0  [vc14]  conda-forge
pep8                      1.7.0                    py36_0
pickleshare               0.7.4                    py36_0
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.1                    py36_1
ply                       3.10                     py36_0
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
prompt_toolkit            1.0.14                   py36_0
psutil                    5.2.2                    py36_0
psycopg2                  2.7.3.2                  py36_0    conda-forge
py                        1.4.33                   py36_0
pyasn1                    0.3.7                     <pip>
pyasn1-modules            0.1.4                     <pip>
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pycrypto                  2.6.1                    py36_6
pycurl                    7.43.0           py36h086bf4c_3
pyflakes                  1.5.0                    py36_0
pygments                  2.2.0                    py36_0
pylint                    1.7.4            py36ha4e6ded_0
pyodbc                    4.0.16                   py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_2
pysal                     1.14.3                   py36_0    conda-forge
pysocks                   1.6.7            py36h698d350_1    anaconda
pytables                  3.4.2                    py36_7    conda-forge
pytest                    3.0.7                    py36_0
python                    3.6.1                         2
python-dateutil           2.6.0                    py36_0
pytz                      2017.2                   py36_0
pywavelets                0.5.2               np112py36_0
pywin32                   220                      py36_2
pyyaml                    3.12                     py36_0
pyzmq                     16.0.2                   py36_0
qt                        5.6.2                    vc14_2  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0
qtconsole                 4.3.0                    py36_0
qtpy                      1.2.1                    py36_0
r-assertthat              0.2.0                  r3.4.1_0
r-backports               1.1.0                  r3.4.1_0
r-base                    3.4.1                         0
r-base64enc               0.1_3                  r3.4.1_0
r-bh                      1.62.0_1               r3.4.1_0
r-bindr                   0.1                    r3.4.1_0
r-bindrcpp                0.2                    r3.4.1_0
r-bitops                  1.0_6                  r3.4.1_2
r-boot                    1.3_19                 r3.4.1_0
r-broom                   0.4.2                  r3.4.1_0
r-car                     2.1_4                  r3.4.1_0
r-caret                   6.0_76                 r3.4.1_0
r-catools                 1.17.1                 r3.4.1_2
r-cellranger              1.1.0                  r3.4.1_0
r-class                   7.3_14                 r3.4.1_0
r-cluster                 2.0.6                  r3.4.1_0
r-codetools               0.2_15                 r3.4.1_0
r-colorspace              1.3_2                  r3.4.1_0
r-crayon                  1.3.2                  r3.4.1_0
r-curl                    2.6                    r3.4.1_0
r-data.table              1.10.4                 r3.4.1_0
r-dbi                     0.6_1                  r3.4.1_0
r-dichromat               2.0_0                  r3.4.1_2
r-digest                  0.6.12                 r3.4.1_0
r-dplyr                   0.7.0                  r3.4.1_0
r-essentials              1.6.0                  r3.4.1_0
r-evaluate                0.10                   r3.4.1_0
r-forcats                 0.2.0                  r3.4.1_0
r-foreach                 1.4.3                  r3.4.1_0
r-foreign                 0.8_68                 r3.4.1_0
r-formatr                 1.5                    r3.4.1_0
r-ggplot2                 2.2.1                  r3.4.1_0
r-gistr                   0.4.0                  r3.4.1_0
r-glmnet                  2.0_10                 r3.4.1_0
r-glue                    1.1.1                  r3.4.1_0
r-gtable                  0.2.0                  r3.4.1_0
r-haven                   1.0.0                  r3.4.1_0
r-hexbin                  1.27.1                 r3.4.1_0
r-highr                   0.6                    r3.4.1_0
r-hms                     0.3                    r3.4.1_0
r-htmltools               0.3.6                  r3.4.1_0
r-htmlwidgets             0.8                    r3.4.1_1
r-httpuv                  1.3.3                  r3.4.1_0
r-httr                    1.2.1                  r3.4.1_0
r-irdisplay               0.4.4                  r3.4.1_0
r-irkernel                0.7.1                  r3.4.1_0
r-iterators               1.0.8                  r3.4.1_0
r-jsonlite                1.5                    r3.4.1_0
r-kernsmooth              2.23_15                r3.4.1_0
r-knitr                   1.16                   r3.4.1_0
r-labeling                0.3                    r3.4.1_2
r-lattice                 0.20_35                r3.4.1_0
r-lazyeval                0.2.0                  r3.4.1_0
r-lme4                    1.1_13                 r3.4.1_0
r-lubridate               1.6.0                  r3.4.1_0
r-magrittr                1.5                    r3.4.1_2
r-maps                    3.2.0                  r3.4.1_0
r-markdown                0.8                    r3.4.1_0
r-mass                    7.3_47                 r3.4.1_0
r-matrix                  1.2_10                 r3.4.1_0
r-matrixmodels            0.4_1                  r3.4.1_0
r-mgcv                    1.8_17                 r3.4.1_0
r-mime                    0.5                    r3.4.1_0
r-minqa                   1.2.4                  r3.4.1_2
r-mnormt                  1.5_5                  r3.4.1_0
r-modelmetrics            1.1.0                  r3.4.1_0
r-modelr                  0.1.0                  r3.4.1_0
r-munsell                 0.4.3                  r3.4.1_0
r-nlme                    3.1_131                r3.4.1_0
r-nloptr                  1.0.4                  r3.4.1_2
r-nnet                    7.3_12                 r3.4.1_0
r-openssl                 0.9.6                  r3.4.1_0
r-packrat                 0.4.8_1                r3.4.1_0
r-pbdzmq                  0.2_6                  r3.4.1_0
r-pbkrtest                0.4_7                  r3.4.1_0
r-pkgconfig               2.0.1                  r3.4.1_0
r-pki                     0.1_3                  r3.4.1_0
r-plogr                   0.1_1                  r3.4.1_0
r-plyr                    1.8.4                  r3.4.1_0
r-pryr                    0.1.2                  r3.4.1_0
r-psych                   1.7.5                  r3.4.1_0
r-purrr                   0.2.2.2                r3.4.1_0
r-quantmod                0.4_9                  r3.4.1_0
r-quantreg                5.33                   r3.4.1_0
r-r6                      2.2.1                  r3.4.1_0
r-randomforest            4.6_12                 r3.4.1_0
r-rbokeh                  0.5.0                  r3.4.1_0
r-rcolorbrewer            1.1_2                  r3.4.1_3
r-rcpp                    0.12.11                r3.4.1_0
r-rcppeigen               0.3.3.3.0              r3.4.1_0
r-rcurl                   1.95_4.8               r3.4.1_0
r-readr                   1.1.1                  r3.4.1_0
r-readxl                  1.0.0                  r3.4.1_0
r-recommended             3.4.1                  r3.4.1_0
r-rematch                 1.0.1                  r3.4.1_0
r-repr                    0.10                   r3.4.1_0
r-reshape2                1.4.2                  r3.4.1_0
r-rjsonio                 1.3_0                  r3.4.1_2
r-rlang                   0.1.1                  r3.4.1_0
r-rmarkdown               1.5                    r3.4.1_0
r-rpart                   4.1_11                 r3.4.1_0
r-rprojroot               1.2                    r3.4.1_0
r-rsconnect               0.8                    r3.4.1_0
r-rstudioapi              0.6                    r3.4.1_0
r-rvest                   0.3.2                  r3.4.1_0
r-scales                  0.4.1                  r3.4.1_0
r-selectr                 0.3_1                  r3.4.1_0
r-shiny                   1.0.3                  r3.4.1_0
r-sourcetools             0.1.6                  r3.4.1_0
r-sparsem                 1.77                   r3.4.1_0
r-spatial                 7.3_11                 r3.4.1_0
r-stringi                 1.1.5                  r3.4.1_0
r-stringr                 1.2.0                  r3.4.1_0
r-survival                2.41_3                 r3.4.1_0
r-tibble                  1.3.3                  r3.4.1_0
r-tidyr                   0.6.3                  r3.4.1_0
r-tidyverse               1.1.1                  r3.4.1_0
r-ttr                     0.23_1                 r3.4.1_0
r-uuid                    0.1_2                  r3.4.1_0
r-xml2                    1.1.1                  r3.4.1_0
r-xtable                  1.8_2                  r3.4.1_0
r-xts                     0.9_7                  r3.4.1_2
r-yaml                    2.1.14                 r3.4.1_0
r-zoo                     1.8_0                  r3.4.1_0
requests                  2.18.4                    <pip>
requests                  2.18.4           py36h4371aae_1    anaconda
rope                      0.9.4                    py36_1
rsa                       3.4.2                     <pip>
rstudio                   1.0.136                  vc14_1  [vc14]
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_1
scikit-image              0.13.0              np112py36_0
scikit-learn              0.18.1              np112py36_1
scipy                     0.19.0              np112py36_0
seaborn                   0.7.1                    py36_0
setuptools                27.2.0                   py36_1
shapely                   1.6.2                    py36_1    conda-forge
simplegeneric             0.8.1                    py36_1
singledispatch            3.4.0.3                  py36_0
sip                       4.18                     py36_0
six                       1.10.0                   py36_0
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                    py36_0
sortedcollections         0.5.3                    py36_0
sortedcontainers          1.5.7                    py36_0
sphinx                    1.5.6                    py36_0
spyder                    3.2.4            py36h8845eaa_0
sqlalchemy                1.1.9                    py36_0
sqlite                    3.13.0                   vc14_0  [vc14]  conda-forge
statsmodels               0.8.0               np112py36_0
sympy                     1.0                      py36_0
tblib                     1.3.2                    py36_0
testpath                  0.3                      py36_0
tk                        8.5.19                   vc14_1  [vc14]  conda-forge
toolz                     0.8.2                    py36_0
tornado                   4.5.1                    py36_0
traitlets                 4.3.2                    py36_0
unicodecsv                0.14.1                   py36_0
uritemplate               3.0.0                     <pip>
urllib3                   1.22             py36h276f60a_0    anaconda
urllib3                   1.22                      <pip>
vc                        14                   h2379b0c_2    anaconda
vega                      0.4.4                    py36_1    conda-forge
vincent                   0.4.4                    py36_0    conda-forge
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py36_0
werkzeug                  0.12.2                   py36_0
wheel                     0.29.0                   py36_0
widgetsnbextension        2.0.0                    py36_0
win_inet_pton             1.0.1            py36he67d7fd_1    anaconda
win_unicode_console       0.5                      py36_0
wrapt                     1.10.10                  py36_0
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xlrd                      1.0.0                    py36_0
xlsxwriter                0.9.6                    py36_0
xlwings                   0.10.4                   py36_0
xlwt                      1.2.0                    py36_0
zict                      0.1.2                    py36_0
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

</details>

#### Code that reproduces the issue

Exactly the one in [notebook 11
](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/11-plot-routes-folium-web-map.ipynb)

Thanks for this package, it is really useful.

**Comment by gboeing** [comment]
I believe the issue you're referring to was resolved by #104. If you install the latest master branch and run it, it should work.

**Comment by IlyaOrson** [comment]
I just installed the master branch and the issue is partially solved. Now the second exaple works (Plot a route as an interactive web map) but the other two still show a blank page.

The package versions that I am using are:
```
osmnx: 0.7.dev0
networkx: 2.0
numpy: 1.13.3
folium: 0.5.0
```

**Comment by gboeing** [comment]
You're right. This has now been fixed by a200620fdcc91bca22611f5052bd6ec3ac0bd5b6.
