### ISSUE TITLE
TopologyException: Input geom 0 is invalid

### ISSUE THREAD

**Issue by BCNecoder** [gboeing/osmnx#330]
####I'm running python 3.7 in Jupyter Notebook in Windows and trying to get the building footprints of Barcelona through the osmnx 0.10 footprints fuction:
```
import osmnx as ox
import matplotlib.pyplot as plt
%matplotlib inline

place_name = "Barcelona, Barcelona, Catalonia, Spain"
graph = ox.graph_from_place(place_name)
buildings = ox.footprints_from_place(place_name)
```
After running the script it yields the following error message:

`#TopologyException: Input geom 0 is invalid: Self-intersection at or near point 2.1664058699463573 41.38391317543983 at 2.1664058699463573 41.38391317543983`

<details>

---
TopologicalError                          Traceback (most recent call last)
<ipython-input-37-fad0a24b83ee> in <module>
      3 
      4 # Retrieve buildings from the area
----> 5 buildings = ox.footprints_from_place(place_name, footprint_type = 'building', retain_invalid = True)
      6 
      7 # What types are those?

C:\Anaconda\lib\site-packages\osmnx\footprints.py in footprints_from_place(place, footprint_type, retain_invalid)
    358     polygon = city['geometry'].iloc[0]
    359     return create_footprints_gdf(polygon, retain_invalid=retain_invalid,
--> 360                                  footprint_type=footprint_type)
    361 
    362 

C:\Anaconda\lib\site-packages\osmnx\footprints.py in create_footprints_gdf(polygon, north, south, east, west, footprint_type, retain_invalid)
    226 
    227                     for inner_poly in inner_polys:
--> 228                         temp_poly=temp_poly.difference(footprints[inner_poly]['geometry'])
    229 
    230                     multipoly.append(temp_poly)

C:\Anaconda\lib\site-packages\shapely\geometry\base.py in difference(self, other)
    614     def difference(self, other):
    615         """Returns the difference of the geometries"""
--> 616         return geom_factory(self.impl['difference'](self, other))
    617 
    618     def intersection(self, other):

C:\Anaconda\lib\site-packages\shapely\topology.py in __call__(self, this, other, *args)
     68             err = TopologicalError(
     69                     "This operation could not be performed. Reason: unknown")
---> 70             self._check_topology(err, this, other)
     71         return product
     72 

C:\Anaconda\lib\site-packages\shapely\topology.py in _check_topology(self, err, *geoms)
     36                     "The operation '%s' could not be performed. "
     37                     "Likely cause is invalidity of the geometry %s" % (
---> 38                         self.fn.__name__, repr(geom)))
     39         raise err
     40 

TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x000001D21A9B6E10>
</details>

**Comment by gboeing** [comment]
This is fixed in the latest code commits and will be released in the next version.

**Comment by havardl** [comment]
@gboeing When running version 0.10 of osmnx (with Python 3.6) I still get this error. Are you referencing a version yet to come?

```python
import geopandas as gpd
import osmnx as ox

ox.config(log_console=True, use_cache=True)
ox.__version__

img_folder = 'images'
extension = 'png'
size = 1000
dpi = 200

query = 'Copenhagen Municipality,Denmark'
gdf = ox.footprints.footprints_from_place(query)
gdf_proj = ox.project_gdf(gdf)
fig, ax = ox.footprints.plot_footprints(gdf_proj, bgcolor='#333333', color='w', 
                            save=True, show=False, close=True, filename='cph', dpi=dpi)
```

Output:
```
Got all footprint data within polygon from API in 1 request(s) and 0.81 seconds
Polygon has invalid geometry: [496207314, 496190671]
Polygon has invalid geometry: [496207309, 496190314]
Polygon has invalid geometry: [496190445, 496190486]
Polygon has invalid geometry: [3556585323, 3556585320]
Polygon has invalid geometry: [3556585322, 3556585321]
Polygon has invalid geometry: [3556585322, 3556585323]
Polygon has invalid geometry: [3556585320, 3556585321]
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 12.569343186775633 55.682462543404455 at 12.569343186775633 55.682462543404455

shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f38b8bc9550>
```

Dependencies:
```
attrs==19.3.0
certifi==2019.9.11
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
cycler==0.10.0
decorator==4.4.1
descartes==1.1.0
Fiona==1.8.9.post2
geopandas==0.6.1
idna==2.8
kiwisolver==1.1.0
matplotlib==3.1.1
munch==2.5.0
networkx==2.4
numpy==1.17.3
osmnx==0.10
pandas==0.25.3
pyparsing==2.4.4
pyproj==2.4.1
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
Rtree==0.8.3
Shapely==1.6.4.post2
six==1.13.0
urllib3==1.25.6
```

**Comment by gboeing** [comment]
Yes.

**Comment by havardl** [comment]
Great! Do you have an idea of when the new version will be released?

**Comment by gboeing** [comment]
ETA is mid December

**Comment by martibosch** [comment]
I believe I have come accross this issue in OSMnx 0.11.4 and Shapely 1.7.0 (both installed via conda-forge). The example is due to [this building](https://www.openstreetmap.org/relation/2693685) and can very easily be reproduced:

```python
import osmnx as ox
from shapely import geometry

bldgs_gdf = ox.footprints_from_point((3.8779162, 11.4941608), distance=100)
```

which raises the following exception:
```
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 11.4940412 3.8778134999999998 at 11.4940412 3.8778134999999998
```

with this Traceback:

```
---------------------------------------------------------------------------
TopologicalError                          Traceback (most recent call last)
<ipython-input-57-6df460860646> in <module>
      1 # get the building geo data frame, project it and delete unnecessary
      2 # columns
----> 3 bldgs_gdf = ox.footprints_from_point((3.8779162, 11.4941608), distance=100)

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/osmnx/footprints.py in footprints_from_point(point, distance, footprint_type, retain_invalid)
    441     bbox = bbox_from_point(point=point, distance=distance)
    442     north, south, east, west = bbox
--> 443     return create_footprints_gdf(north=north, south=south, east=east, west=west,
    444                                  footprint_type=footprint_type, retain_invalid=retain_invalid)
    445 

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/osmnx/footprints.py in create_footprints_gdf(polygon, north, south, east, west, footprint_type, retain_invalid, responses)
    185     # create a complex Shapely Polygon or MultiPolygon for each relation
    186     for relation_key, relation_val in relations.items():
--> 187         relation_val['geometry'] = create_relation_geometry(relation_key, relation_val, footprints)
    188 
    189     # merge relations into the footprints dictionary

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/osmnx/footprints.py in create_relation_geometry(relation_key, relation_val, footprints)
    406             for inner_poly in inner_polys:
    407                 if inner_poly.within(outer_poly):
--> 408                     temp_poly=temp_poly.difference(inner_poly)
    409             multipoly.append(temp_poly)
    410 

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/shapely/geometry/base.py in difference(self, other)
    643     def difference(self, other):
    644         """Returns the difference of the geometries"""
--> 645         return geom_factory(self.impl['difference'](self, other))
    646 
    647     def intersection(self, other):

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/shapely/topology.py in __call__(self, this, other, *args)
     68             err = TopologicalError(
     69                     "This operation could not be performed. Reason: unknown")
---> 70             self._check_topology(err, this, other)
     71         return product
     72 

~/anaconda3/envs/mototaxi-trip-analysis/lib/python3.8/site-packages/shapely/topology.py in _check_topology(self, err, *geoms)
     33         for geom in geoms:
     34             if not geom.is_valid:
---> 35                 raise TopologicalError(
     36                     "The operation '%s' could not be performed. "
     37                     "Likely cause is invalidity of the geometry %s" % (

TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f83d5576640>
```

any idea on how to deal with this?

Thanks in advance,
Martí

**Comment by AtelierLibre** [comment]
Hi Martí,

In your example the OSM geometry did indeed include a self-intersection.

Fixing the geometry in OSM [(see here)](https://wiki.openstreetmap.org/wiki/OSM_Inspector/Fixing_self_intersections#The_different_Error_Types) has resolved the issue I think.

Nick

**Comment by martibosch** [comment]
Hello,

thank you for the clarification - I was not aware of such issues. Nonetheless, I wonder whether it would be appropriate to provide a way of retrieving the footprints of given area of interest despite the presence of self-intersections, e.g., with a `topological_errors` argument that can be set to `ignore` and `raise`, where the former catches shapely's `TopologicalError` and just omits the respective relation (so the user can after all retrieve the valid geometries in the area of interest), and the latter raises the exception as OSM currently does.

In my case, I monkey-patched the `create_footprints_gdf` while modifying [the lines 185-187](https://github.com/gboeing/osmnx/blob/68f20ebd9dde80073b66f4a14d5e532278a12c4a/osmnx/footprints.py#L185-L187) as in:

```python
# create a complex Shapely Polygon or MultiPolygon for each relation
topo_error_keys = []
for relation_key, relation_val in relations.items():
    try:
        relation_val['geometry'] = ox.create_relation_geometry(
            relation_key, relation_val, footprints)
    except geos.TopologicalError:
        # The relation contains a self-intersection and will thus not be
        # included in the final footprint gdf
        topo_error_keys.append(relation_key)

# delete keys with topological errors
for relation in topo_error_keys:
    del relations[relation]
```

Best,
Martí

**Comment by AtelierLibre** [comment]
Hi Martí,

I would agree that failing nicely with a warning, omitting the invalid geometry and then listing it (probably in a log) would be an improvement on just stopping as it does now.

Thanks for including your code suggestion, would you be able to raise this in a new separate issue?

All the best,
Nick

**Comment by gboeing** [comment]
@martibosch @AtelierLibre see proposed fix in #406
